  /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.VhscClientes;
import bean.VhscFuncionarios;
import bean.VhscProdutos;
import bean.VhscVendas;
import bean.VhscVendasProdutos;
import dao.vhsc_ClientesDAO;
import dao.vhsc_FuncionariosDAO;
import dao.vhsc_ProdutosDAO;
import dao.vhsc_VendasDAO;
import dao.vhsc_VendasProdutosDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import tools.VHSC_Util;

/**
 *
 * @author Vitor
 */
public class VHSC_JDlgVendas extends javax.swing.JDialog {

    VHSC_ControllerVendasProdutos controllerVendasProd;
    /**
     * Creates new form VHSC_JDlgVendas
     */
    private boolean incluir;

    /**
     * Creates new form VHSC_JDlgVendas
     */
    public VHSC_JDlgVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        setTitle("Cadastro de Vendas");
        vhsc_ClientesDAO clientesDAO = new vhsc_ClientesDAO();
        List lista = (List) clientesDAO.listAll();
        for (int i = 0; i < lista.size(); i++) {
            VHSC_jCboClientes.addItem((VhscClientes) lista.get(i));
        }

        vhsc_FuncionariosDAO funcionariosDAO = new vhsc_FuncionariosDAO();
        List listaVend = (List) funcionariosDAO.listAll();
        for (Object object : listaVend) {
            VHSC_jCboFuncionarios.addItem((VhscFuncionarios) object);
        }
        controllerVendasProd = new VHSC_ControllerVendasProdutos();
        controllerVendasProd.setList(new ArrayList());
        jTable2.setModel(controllerVendasProd);

        VHSC_Util.habilitar(false, VHSC_jTxtValorTotal, VHSC_jTxtCodigo, VHSC_jFmtDataVenda,
                VHSC_jCboClientes, VHSC_jCboFuncionarios, jBtnConfirmar, jBtnCancelar, VHSC_jTxtQuantidade, VHSC_jFmtFormaPagamento, VHSC_jBtnExcluirProd, VHSC_JBtnIncluirProd, VHSC_JBtnAlterarProd);
    }

    public void beanView(VhscVendas vhscVendas) {
        VHSC_jTxtCodigo.setText(VHSC_Util.intToStr(vhscVendas.getVhscIdVenda()));
        VHSC_jTxtValorTotal.setText(VHSC_Util.doubleToStr(vhscVendas.getVhscValorTotal()));
        VHSC_jFmtDataVenda.setText(VHSC_Util.dateToStr(vhscVendas.getVhscDataVenda()));
        VHSC_jCboClientes.setSelectedItem(vhscVendas.getVhscClientes());
        VHSC_jCboFuncionarios.setSelectedItem(vhscVendas.getVhscFuncionarios());
        VHSC_jFmtFormaPagamento.setText(vhscVendas.getVhscFormaPagamento());
        VHSC_jTxtQuantidade.setText(VHSC_Util.intToStr(vhscVendas.getVhscQuantidade()));

        vhsc_VendasProdutosDAO vhsc_vendasProdutosDAO = new vhsc_VendasProdutosDAO();
        List lista = (List) vhsc_vendasProdutosDAO.listProdutos(vhscVendas);
        controllerVendasProd.setList(lista);

    }

    public JTable getjTable1() {
        return jTable2;
    }

    public VhscVendas viewBean() {
        VhscVendas vhscVendas = new VhscVendas();

        vhscVendas.setVhscIdVenda(VHSC_Util.strToInt(VHSC_jTxtCodigo.getText()));
        vhscVendas.setVhscQuantidade(VHSC_Util.strToInt(VHSC_jTxtQuantidade.getText()));
        vhscVendas.setVhscFormaPagamento(VHSC_jFmtFormaPagamento.getText());
        vhscVendas.setVhscClientes((VhscClientes) VHSC_jCboClientes.getSelectedItem());
        vhscVendas.setVhscFuncionarios((VhscFuncionarios) VHSC_jCboFuncionarios.getSelectedItem());
        vhscVendas.setVhscDataVenda(VHSC_Util.strToDate(VHSC_jFmtDataVenda.getText()));
        vhscVendas.setVhscValorTotal(VHSC_Util.strToDouble(VHSC_jTxtValorTotal.getText()));
        return vhscVendas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        VHSC_jFmtDataVenda = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        VHSC_JBtnIncluirProd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        VHSC_JBtnAlterarProd = new javax.swing.JButton();
        VHSC_jTxtCodigo = new javax.swing.JTextField();
        VHSC_jBtnExcluirProd = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        JBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        VHSC_jTxtValorTotal = new javax.swing.JTextField();
        jBtnConfirmar = new javax.swing.JButton();
        VHSC_jCboClientes = new javax.swing.JComboBox<VhscClientes>();
        VHSC_jCboFuncionarios = new javax.swing.JComboBox<VhscFuncionarios>();
        VHSC_jTxtQuantidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        VHSC_jFmtFormaPagamento = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Data venda");

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor total");

        try {
            VHSC_jFmtDataVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        VHSC_jFmtDataVenda.setText("   /  /    ");
        VHSC_jFmtDataVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jFmtDataVendaActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente");

        VHSC_JBtnIncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        VHSC_JBtnIncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_JBtnIncluirProdActionPerformed(evt);
            }
        });

        jLabel1.setText("Num vendas");

        VHSC_JBtnAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        VHSC_JBtnAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_JBtnAlterarProdActionPerformed(evt);
            }
        });

        VHSC_jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jTxtCodigoActionPerformed(evt);
            }
        });

        VHSC_jBtnExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        VHSC_jBtnExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jBtnExcluirProdActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTable2);

        JBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        JBtnAlterar.setText("Alterar");
        JBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jLabel7.setText("Funcionarios");

        VHSC_jTxtValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jTxtValorTotalActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        VHSC_jCboClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jCboClientesActionPerformed(evt);
            }
        });

        VHSC_jCboFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jCboFuncionariosActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade");

        jLabel4.setText("Forma de pagamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VHSC_JBtnAlterarProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VHSC_JBtnIncluirProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VHSC_jBtnExcluirProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBtnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnExcluir)
                                .addGap(21, 21, 21)
                                .addComponent(jBtnConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnPesquisar)
                                .addGap(0, 8, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(VHSC_jTxtCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(VHSC_jFmtDataVenda)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(VHSC_jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(jLabel4)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(VHSC_jFmtFormaPagamento)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(VHSC_jCboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(VHSC_jCboFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(VHSC_jTxtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(VHSC_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VHSC_jFmtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VHSC_jCboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(3, 3, 3))
                        .addComponent(VHSC_jTxtValorTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(VHSC_jCboFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VHSC_jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VHSC_jFmtFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(VHSC_JBtnIncluirProd)
                        .addGap(14, 14, 14)
                        .addComponent(VHSC_JBtnAlterarProd)
                        .addGap(15, 15, 15)
                        .addComponent(VHSC_jBtnExcluirProd))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnIncluir)
                        .addComponent(jBtnExcluir)
                        .addComponent(jBtnConfirmar)
                        .addComponent(jBtnCancelar)
                        .addComponent(JBtnAlterar))
                    .addComponent(jBtnPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        //desabilita  //desabilitar()
        VHSC_Util.habilitar(false, VHSC_jTxtValorTotal, VHSC_jTxtCodigo, VHSC_jFmtDataVenda,
                VHSC_jCboClientes, VHSC_jCboFuncionarios, jBtnConfirmar, jBtnCancelar, VHSC_jFmtFormaPagamento, VHSC_jTxtQuantidade, VHSC_jBtnExcluirProd, VHSC_JBtnIncluirProd, VHSC_JBtnAlterarProd);

        VHSC_Util.habilitar(true, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar);

        VHSC_Util.limpar(VHSC_jTxtValorTotal, VHSC_jTxtCodigo, VHSC_jFmtDataVenda,
                VHSC_jCboClientes, VHSC_jCboFuncionarios, VHSC_jFmtFormaPagamento, VHSC_jTxtQuantidade);
        controllerVendasProd.setList(new ArrayList());

    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        VHSC_JDlgVendasPesquisar vhsc_JDlgVendasPesquisar = new VHSC_JDlgVendasPesquisar(null, true);
        vhsc_JDlgVendasPesquisar.setTelaAnterior(this);
        vhsc_JDlgVendasPesquisar.setVisible(true);

    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void VHSC_jFmtDataVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jFmtDataVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VHSC_jFmtDataVendaActionPerformed

    private void VHSC_JBtnIncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_JBtnIncluirProdActionPerformed
        // TODO add your handling code here:
        VHSC_JDlgVendasProdutos jDlgVendasProdutos = new VHSC_JDlgVendasProdutos(null, true);
        jDlgVendasProdutos.setTelaAnterior(this, null);
        jDlgVendasProdutos.setVisible(true);
        somaTotal();

    }//GEN-LAST:event_VHSC_JBtnIncluirProdActionPerformed

    private void VHSC_JBtnAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_JBtnAlterarProdActionPerformed
        if (jTable2.getSelectedRow() == -1) {
            VHSC_Util.mensagem("Selecione uma linha para Alterar.");
        } else {
            VHSC_JDlgVendasProdutos VHSC_jDlgVendasProdutos = new VHSC_JDlgVendasProdutos(null, true);
            VhscVendasProdutos VhscVendasProdutos = controllerVendasProd.getBean(jTable2.getSelectedRow());
            VHSC_jDlgVendasProdutos.setTelaAnterior(this, VhscVendasProdutos);
            VHSC_jDlgVendasProdutos.setVisible(true);
        }
    }//GEN-LAST:event_VHSC_JBtnAlterarProdActionPerformed

    private void VHSC_jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VHSC_jTxtCodigoActionPerformed

    private void VHSC_jBtnExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jBtnExcluirProdActionPerformed
        // TODO add your handling code here:
        if (jTable2.getSelectedRow() == -1) {
            VHSC_Util.mensagem("Selecione uma linha para Excluir.");
        } else {
            if (VHSC_Util.pergunta("Deseja excluir o produto ?") == true) {
                controllerVendasProd.removeBean(jTable2.getSelectedRow());
            }
        }
        somaTotal();
    }//GEN-LAST:event_VHSC_jBtnExcluirProdActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        VHSC_Util.habilitar(true,  VHSC_jTxtCodigo, VHSC_jFmtDataVenda,
                VHSC_jCboClientes, VHSC_jCboFuncionarios, jBtnConfirmar, jBtnCancelar, VHSC_jFmtFormaPagamento, VHSC_jTxtQuantidade, VHSC_jBtnExcluirProd, VHSC_JBtnIncluirProd, VHSC_JBtnAlterarProd);
        VHSC_Util.habilitar(false, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar);
        VHSC_Util.limpar(VHSC_jTxtValorTotal, VHSC_jTxtCodigo, VHSC_jFmtDataVenda,
                VHSC_jCboClientes, VHSC_jCboFuncionarios, VHSC_jFmtFormaPagamento, VHSC_jTxtQuantidade);

        incluir = true;
        somaTotal();
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void JBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAlterarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (VHSC_jTxtCodigo.getText().trim().isEmpty()) {
            VHSC_Util.mensagem("Pesquise antes de Alterar.");
            return;
        }

        VHSC_Util.habilitar(true,  VHSC_jFmtDataVenda,
                VHSC_jCboClientes, VHSC_jCboFuncionarios, jBtnConfirmar, jBtnCancelar, VHSC_jFmtFormaPagamento, VHSC_jTxtQuantidade, VHSC_jBtnExcluirProd, VHSC_JBtnIncluirProd, VHSC_JBtnAlterarProd);
        VHSC_Util.habilitar(false, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar, VHSC_jTxtCodigo);

        incluir = false;
    }//GEN-LAST:event_JBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (VHSC_jTxtCodigo.getText().trim().isEmpty()) {
            VHSC_Util.mensagem("Pesquise antes de Excluir.");
            return;
        }

        if (VHSC_Util.pergunta("Deseja excluir ?") == true) {

            vhsc_VendasDAO vendasDAO = new vhsc_VendasDAO();
            vhsc_VendasProdutosDAO vendasProdutosDAO = new vhsc_VendasProdutosDAO();
            VhscVendas venda = viewBean();
            vendasProdutosDAO.deleteProdutos(venda);
            vendasDAO.delete(venda);
            VHSC_Util.limpar(VHSC_jTxtValorTotal, VHSC_jTxtCodigo, VHSC_jFmtDataVenda,
                    VHSC_jCboClientes, VHSC_jCboFuncionarios, VHSC_jFmtFormaPagamento, VHSC_jTxtQuantidade);

            controllerVendasProd.setList(new ArrayList());
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        //desabilitar();
        //desabilitar();
        vhsc_VendasDAO vhsc_vendasDAO = new vhsc_VendasDAO();
        vhsc_VendasProdutosDAO vhsc_vendasProdutosDAO = new vhsc_VendasProdutosDAO();
        VhscVendas vhscVendas = viewBean();
        if (incluir == true) {
            vhsc_vendasDAO.insert(vhscVendas);
            for (int ind = 0; ind < jTable2.getRowCount(); ind++) {
                VhscVendasProdutos vendasProdutos = controllerVendasProd.getBean(ind);
                vendasProdutos.setVhscVendas(vhscVendas);
                vhsc_vendasProdutosDAO.insert(vendasProdutos);
            }
        } else {
            vhsc_vendasDAO.update(vhscVendas);
            //excluo todos os pedidos produtos do pedido
            vhsc_vendasProdutosDAO.deleteProdutos(vhscVendas);
            //incluo os pedidos produtos
            for (int ind = 0; ind < jTable2.getRowCount(); ind++) {
                VhscVendasProdutos vendasProdutos = controllerVendasProd.getBean(ind);
                vendasProdutos.setVhscVendas(vhscVendas);
                vhsc_vendasProdutosDAO.insert(vendasProdutos);
            }
        }

        VHSC_Util.habilitar(false, VHSC_jTxtValorTotal, VHSC_jTxtCodigo, VHSC_jFmtDataVenda,
                VHSC_jCboFuncionarios, VHSC_jCboClientes, jBtnConfirmar, jBtnCancelar, VHSC_jFmtFormaPagamento, VHSC_jTxtQuantidade,VHSC_jBtnExcluirProd, VHSC_JBtnIncluirProd, VHSC_JBtnAlterarProd);

        VHSC_Util.habilitar(true, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar);

        VHSC_Util.limpar(VHSC_jTxtValorTotal, VHSC_jTxtCodigo, VHSC_jFmtDataVenda,
                VHSC_jCboClientes, VHSC_jCboFuncionarios, VHSC_jFmtFormaPagamento, VHSC_jTxtQuantidade);
        controllerVendasProd.setList(new ArrayList());

    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void VHSC_jCboClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jCboClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VHSC_jCboClientesActionPerformed

    private void VHSC_jTxtValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jTxtValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VHSC_jTxtValorTotalActionPerformed

    private void jTable2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2AncestorAdded

    private void VHSC_jCboFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jCboFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VHSC_jCboFuncionariosActionPerformed
public void somaTotal() {
        double somaTotais = 0.0;

        for (int i = 0; i < jTable2.getRowCount(); i++) {
            Object valorTotal = jTable2.getValueAt(i, 4);
            if (valorTotal != null) {
                somaTotais += VHSC_Util.strToDouble(valorTotal.toString());
            }
        }

        VHSC_jTxtValorTotal.setText(VHSC_Util.doubleToStr(somaTotais));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VHSC_JDlgVendas dialog = new VHSC_JDlgVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAlterar;
    private javax.swing.JButton VHSC_JBtnAlterarProd;
    private javax.swing.JButton VHSC_JBtnIncluirProd;
    private javax.swing.JButton VHSC_jBtnExcluirProd;
    private javax.swing.JComboBox<VhscClientes> VHSC_jCboClientes;
    private javax.swing.JComboBox<VhscFuncionarios> VHSC_jCboFuncionarios;
    private javax.swing.JFormattedTextField VHSC_jFmtDataVenda;
    private javax.swing.JFormattedTextField VHSC_jFmtFormaPagamento;
    private javax.swing.JTextField VHSC_jTxtCodigo;
    private javax.swing.JTextField VHSC_jTxtQuantidade;
    private javax.swing.JTextField VHSC_jTxtValorTotal;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
