/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.VhscClientes;
import dao.vhsc_ClientesDAO;
import javax.swing.JOptionPane;
import tools.VHSC_Util;

/**
 *
 * @author Vitor
 */
public class VHSC_JDlgClientes extends javax.swing.JDialog {
private boolean incluir;
    /**
     * Creates new form VHSC_JDlgClientes
     */
    public VHSC_JDlgClientes(java.awt.Frame parent, boolean modal) {
      super(parent, modal);
        initComponents();
        setTitle("Cadastro de Clientes");
        setLocationRelativeTo(null);
        VHSC_Util.habilitar(false, VHSC_jTxtNome, VHSC_jTxtCodigo, VHSC_jFmtDataNascimento,VHSC_jFmtCpf, VHSC_jTxtEndereco
        , VHSC_jFmtTelefone, VHSC_jTxtEmail, VHSC_jChbAtivo, VHSC_jCboGenero,VHSC_jFmtDataCadastro, VHSC_jFmtCep, VHSC_jFmtEstado, 
        VHSC_jTxtCidade, VHSC_jTxtObservacoes, VHSC_jTxtRendaMensal ,jBtnConfirmar,jBtnCancelar);
    }
     public void beanView(VhscClientes vhscClientes) {
        VHSC_jTxtCodigo.setText(VHSC_Util.intToStr(vhscClientes.getVhscIdCliente()));
        VHSC_jTxtNome.setText(vhscClientes.getVhscNome());
        VHSC_jFmtCpf.setText(vhscClientes.getVhscCpf());
        VHSC_jFmtDataNascimento.setText(VHSC_Util.dateToStr(vhscClientes.getVhscDataNascimento()));
        VHSC_jTxtEndereco.setText(vhscClientes.getVhscEndereco());
        VHSC_jFmtTelefone.setText(vhscClientes.getVhscTelefone());
        VHSC_jTxtEmail.setText(vhscClientes.getVhscEmail());
        VHSC_jFmtCep.setText(vhscClientes.getVhscCep());
        VHSC_jFmtDataCadastro.setText(VHSC_Util.dateToStr(vhscClientes.getVhscDataCadastro()));
        VHSC_jFmtEstado.setText(vhscClientes.getVhscEstado());
        VHSC_jTxtCidade.setText(vhscClientes.getVhscCidade());
        VHSC_jTxtObservacoes.setText(vhscClientes.getVhscObservacoes());
        VHSC_jTxtRendaMensal.setText(vhscClientes.getVhscRendaMensal());
        VHSC_jCboGenero.setSelectedIndex(vhscClientes.getVhscGenero());

          if (vhscClientes.getVhscAtivo().equals("S") == true) {
            VHSC_jChbAtivo.setSelected(true);
        } else {
            VHSC_jChbAtivo.setSelected(false);
        }
        
     }
     public VhscClientes viewBean() {
    VhscClientes vhscClientes = new VhscClientes();
        int codigo = VHSC_Util.strToInt(VHSC_jTxtCodigo.getText());
        vhscClientes.setVhscIdCliente(codigo);
        
    vhscClientes.setVhscNome(VHSC_jTxtNome.getText());
    vhscClientes.setVhscCpf(VHSC_jFmtCpf.getText());
    vhscClientes.setVhscDataNascimento(VHSC_Util.strToDate(VHSC_jFmtDataNascimento.getText()));
    vhscClientes.setVhscEndereco(VHSC_jTxtEndereco.getText());
    vhscClientes.setVhscTelefone(VHSC_jFmtTelefone.getText());
    vhscClientes.setVhscEmail(VHSC_jTxtEmail.getText());
    vhscClientes.setVhscCep(VHSC_jFmtCep.getText());
    vhscClientes.setVhscDataCadastro(VHSC_Util.strToDate(VHSC_jFmtDataCadastro.getText()));
    vhscClientes.setVhscEstado(VHSC_jFmtEstado.getText());
    vhscClientes.setVhscCidade(VHSC_jTxtCidade.getText());
    vhscClientes.setVhscObservacoes(VHSC_jTxtObservacoes.getText());
    vhscClientes.setVhscRendaMensal(VHSC_jTxtRendaMensal.getText());
    vhscClientes.setVhscGenero(VHSC_jCboGenero.getSelectedIndex());
    
      if (VHSC_jChbAtivo.isSelected() == true) {
        vhscClientes.setVhscAtivo("S");
    } else {
        vhscClientes.setVhscAtivo("N");
    }
    
    
    return vhscClientes;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VHSC_jTxtEndereco = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        VHSC_jTxtRendaMensal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        VHSC_jTxtObservacoes = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        VHSC_jFmtEstado = new javax.swing.JFormattedTextField();
        VHSC_jFmtCpf = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        VHSC_jFmtTelefone = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        VHSC_jFmtDataCadastro = new javax.swing.JFormattedTextField();
        VHSC_jTxtEmail = new javax.swing.JTextField();
        VHSC_jFmtCep = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        VHSC_jTxtCodigo = new javax.swing.JTextField();
        VHSC_jCboGenero = new javax.swing.JComboBox<String>();
        VHSC_jTxtNome = new javax.swing.JTextField();
        VHSC_jChbAtivo = new javax.swing.JCheckBox();
        VHSC_jFmtDataNascimento = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jBtnIncluir = new javax.swing.JButton();
        JBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        VHSC_jTxtCidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        VHSC_jTxtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jTxtEnderecoActionPerformed(evt);
            }
        });

        jLabel12.setText("DataCadastro");

        VHSC_jTxtRendaMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jTxtRendaMensalActionPerformed(evt);
            }
        });

        jLabel13.setText("Genero");

        jLabel15.setText("RendaMensal");

        VHSC_jTxtObservacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jTxtObservacoesActionPerformed(evt);
            }
        });

        jLabel16.setText("Observações");

        jLabel3.setText("Estado");

        try {
            VHSC_jFmtEstado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        VHSC_jFmtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jFmtEstadoActionPerformed(evt);
            }
        });

        try {
            VHSC_jFmtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        VHSC_jFmtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jFmtCpfActionPerformed(evt);
            }
        });

        jLabel8.setText("Email");

        try {
            VHSC_jFmtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        VHSC_jFmtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jFmtTelefoneActionPerformed(evt);
            }
        });

        jLabel6.setText("Telefone");

        try {
            VHSC_jFmtDataCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        VHSC_jFmtDataCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jFmtDataCadastroActionPerformed(evt);
            }
        });

        VHSC_jTxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jTxtEmailActionPerformed(evt);
            }
        });

        try {
            VHSC_jFmtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        VHSC_jFmtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jFmtCepActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo");

        jLabel2.setText("Nome");

        VHSC_jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jTxtCodigoActionPerformed(evt);
            }
        });

        VHSC_jCboGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        VHSC_jCboGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jCboGeneroActionPerformed(evt);
            }
        });

        VHSC_jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jTxtNomeActionPerformed(evt);
            }
        });

        VHSC_jChbAtivo.setText("Ativo");
        VHSC_jChbAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jChbAtivoActionPerformed(evt);
            }
        });

        try {
            VHSC_jFmtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        VHSC_jFmtDataNascimento.setToolTipText("");
        VHSC_jFmtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jFmtDataNascimentoActionPerformed(evt);
            }
        });

        jLabel7.setText("Endereço");

        jLabel10.setText("Cidade");

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluir.setMnemonic('I');
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        JBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        JBtnAlterar.setText("Alterar");
        JBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLabel4.setText("Cpf");

        jLabel5.setText("Data Nascimento");

        jLabel11.setText("Cep");

        VHSC_jTxtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jTxtCidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnPesquisar)
                .addGap(60, 60, 60))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(VHSC_jTxtCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                            .addComponent(VHSC_jTxtNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VHSC_jTxtEmail, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(VHSC_jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4)
                                        .addComponent(VHSC_jFmtCpf)
                                        .addComponent(VHSC_jFmtCep, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(VHSC_jFmtDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addComponent(VHSC_jTxtCidade)
                                        .addComponent(jLabel15)
                                        .addComponent(VHSC_jTxtRendaMensal)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(VHSC_jTxtObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(VHSC_jCboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(VHSC_jChbAtivo)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3)
                                .addComponent(jLabel12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(VHSC_jFmtDataCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(VHSC_jFmtTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VHSC_jFmtEstado, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(376, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jBtnExcluir)
                    .addComponent(JBtnAlterar)
                    .addComponent(jBtnIncluir))
                .addGap(14, 14, 14))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(VHSC_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(VHSC_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(VHSC_jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(VHSC_jFmtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VHSC_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VHSC_jFmtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel10)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(VHSC_jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VHSC_jTxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VHSC_jFmtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel15))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(VHSC_jTxtRendaMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VHSC_jFmtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VHSC_jFmtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(VHSC_jTxtObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(VHSC_jCboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VHSC_jChbAtivo))))
                    .addContainerGap(86, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VHSC_jTxtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jTxtEnderecoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_VHSC_jTxtEnderecoActionPerformed

    private void VHSC_jTxtRendaMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jTxtRendaMensalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_VHSC_jTxtRendaMensalActionPerformed

    private void VHSC_jTxtObservacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jTxtObservacoesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_VHSC_jTxtObservacoesActionPerformed

    private void VHSC_jFmtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jFmtEstadoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_VHSC_jFmtEstadoActionPerformed

    private void VHSC_jFmtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jFmtCpfActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_VHSC_jFmtCpfActionPerformed

    private void VHSC_jFmtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jFmtTelefoneActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_VHSC_jFmtTelefoneActionPerformed

    private void VHSC_jFmtDataCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jFmtDataCadastroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_VHSC_jFmtDataCadastroActionPerformed

    private void VHSC_jTxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jTxtEmailActionPerformed
       
    }//GEN-LAST:event_VHSC_jTxtEmailActionPerformed

    private void VHSC_jFmtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jFmtCepActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_VHSC_jFmtCepActionPerformed

    private void VHSC_jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jTxtCodigoActionPerformed
        
    }//GEN-LAST:event_VHSC_jTxtCodigoActionPerformed

    private void VHSC_jCboGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jCboGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VHSC_jCboGeneroActionPerformed

    private void VHSC_jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jTxtNomeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_VHSC_jTxtNomeActionPerformed

    private void VHSC_jChbAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jChbAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VHSC_jChbAtivoActionPerformed

    private void VHSC_jFmtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jFmtDataNascimentoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_VHSC_jFmtDataNascimentoActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        VHSC_Util.habilitar(true, VHSC_jTxtNome, VHSC_jTxtCodigo, VHSC_jFmtDataNascimento,VHSC_jFmtCpf, VHSC_jTxtEndereco
        , VHSC_jFmtTelefone, VHSC_jTxtEmail, VHSC_jChbAtivo, VHSC_jCboGenero,VHSC_jFmtDataCadastro, VHSC_jFmtCep, VHSC_jFmtEstado, 
        VHSC_jTxtCidade, VHSC_jTxtObservacoes, VHSC_jTxtRendaMensal,jBtnConfirmar,jBtnCancelar);
         VHSC_Util.habilitar(false, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar);
    incluir = true;
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void JBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAlterarActionPerformed
        // TODO add your handling code here:]
          if (VHSC_jTxtCodigo.getText().trim().isEmpty()) {
        VHSC_Util.mensagem("Pesquise antes de Alterar.");
        return;
    }
        VHSC_Util.habilitar(true, VHSC_jTxtNome,VHSC_jFmtDataNascimento,VHSC_jFmtCpf, VHSC_jTxtEndereco
        , VHSC_jFmtTelefone, VHSC_jTxtEmail, VHSC_jChbAtivo, VHSC_jCboGenero,VHSC_jFmtDataCadastro, VHSC_jFmtCep, VHSC_jFmtEstado, 
        VHSC_jTxtCidade, VHSC_jTxtObservacoes, VHSC_jTxtRendaMensal,jBtnConfirmar,jBtnCancelar);
         VHSC_Util.habilitar(false, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar,VHSC_jTxtCodigo);
         incluir = false;
    }//GEN-LAST:event_JBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
if (VHSC_jTxtCodigo.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Pesquise um usuário antes de excluir.");
        return;}
        // TODO add your handling code here:

         if (VHSC_Util.pergunta("Deseja excluir ?") == true) {
            vhsc_ClientesDAO vhsc_clientesDAO = new vhsc_ClientesDAO();
            vhsc_clientesDAO.delete(viewBean());
        }
       VHSC_Util.limpar(VHSC_jTxtNome, VHSC_jTxtCodigo, VHSC_jFmtDataNascimento,VHSC_jFmtCpf, VHSC_jTxtEndereco
        , VHSC_jFmtTelefone, VHSC_jTxtEmail, VHSC_jChbAtivo, VHSC_jCboGenero,VHSC_jFmtDataCadastro, VHSC_jFmtCep, VHSC_jFmtEstado, 
        VHSC_jTxtCidade, VHSC_jTxtObservacoes, VHSC_jTxtRendaMensal);
       
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        
        vhsc_ClientesDAO vhsc_clientesDAO = new vhsc_ClientesDAO();
        VhscClientes vhscClientes = viewBean();
        if (incluir == true) {
            vhsc_clientesDAO.insert(vhscClientes);
            //usuariosDAO.insert( viewBean() );
        } else {
            vhsc_clientesDAO.update(vhscClientes);
            //usuariosDAO.update( viewBean() );
        }
        
       VHSC_Util.habilitar(false, VHSC_jTxtNome, VHSC_jTxtCodigo, VHSC_jFmtDataNascimento,VHSC_jFmtCpf, VHSC_jTxtEndereco
        , VHSC_jFmtTelefone, VHSC_jTxtEmail, VHSC_jChbAtivo, VHSC_jCboGenero,VHSC_jFmtDataCadastro, VHSC_jFmtCep, VHSC_jFmtEstado, 
        VHSC_jTxtCidade, VHSC_jTxtObservacoes, VHSC_jTxtRendaMensal,jBtnConfirmar,jBtnCancelar);
       
         VHSC_Util.habilitar(true, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar);
         
              VHSC_Util.limpar(VHSC_jTxtNome, VHSC_jTxtCodigo, VHSC_jFmtDataNascimento,VHSC_jFmtCpf, VHSC_jTxtEndereco
        , VHSC_jFmtTelefone, VHSC_jTxtEmail, VHSC_jChbAtivo, VHSC_jCboGenero,VHSC_jFmtDataCadastro, VHSC_jFmtCep, VHSC_jFmtEstado, 
        VHSC_jTxtCidade, VHSC_jTxtObservacoes, VHSC_jTxtRendaMensal);
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        //desabilitar()
        VHSC_Util.habilitar(false,VHSC_jTxtNome, VHSC_jTxtCodigo, VHSC_jFmtDataNascimento,VHSC_jFmtCpf, VHSC_jTxtEndereco
        , VHSC_jFmtTelefone, VHSC_jTxtEmail, VHSC_jChbAtivo, VHSC_jCboGenero,VHSC_jFmtDataCadastro, VHSC_jFmtCep, VHSC_jFmtEstado, 
        VHSC_jTxtCidade, VHSC_jTxtObservacoes, VHSC_jTxtRendaMensal , jBtnConfirmar,jBtnCancelar);
        
         VHSC_Util.habilitar(true, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar);
         
          VHSC_Util.limpar(VHSC_jTxtNome, VHSC_jTxtCodigo, VHSC_jFmtDataNascimento,VHSC_jFmtCpf, VHSC_jTxtEndereco
        , VHSC_jFmtTelefone, VHSC_jTxtEmail, VHSC_jChbAtivo, VHSC_jCboGenero,VHSC_jFmtDataCadastro, VHSC_jFmtCep, VHSC_jFmtEstado, 
        VHSC_jTxtCidade, VHSC_jTxtObservacoes, VHSC_jTxtRendaMensal);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
      VHSC_JDlgClientesPesquisar vhsc_JDlgClientesPesquisar = new VHSC_JDlgClientesPesquisar(null, true);
        vhsc_JDlgClientesPesquisar.setTelaAnterior(this);
        vhsc_JDlgClientesPesquisar.setVisible(true);

    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void VHSC_jTxtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jTxtCidadeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_VHSC_jTxtCidadeActionPerformed
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VHSC_JDlgClientes dialog = new VHSC_JDlgClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAlterar;
    private javax.swing.JComboBox<String> VHSC_jCboGenero;
    private javax.swing.JCheckBox VHSC_jChbAtivo;
    private javax.swing.JFormattedTextField VHSC_jFmtCep;
    private javax.swing.JFormattedTextField VHSC_jFmtCpf;
    private javax.swing.JFormattedTextField VHSC_jFmtDataCadastro;
    private javax.swing.JFormattedTextField VHSC_jFmtDataNascimento;
    private javax.swing.JFormattedTextField VHSC_jFmtEstado;
    private javax.swing.JFormattedTextField VHSC_jFmtTelefone;
    private javax.swing.JTextField VHSC_jTxtCidade;
    private javax.swing.JTextField VHSC_jTxtCodigo;
    private javax.swing.JTextField VHSC_jTxtEmail;
    private javax.swing.JTextField VHSC_jTxtEndereco;
    private javax.swing.JTextField VHSC_jTxtNome;
    private javax.swing.JTextField VHSC_jTxtObservacoes;
    private javax.swing.JTextField VHSC_jTxtRendaMensal;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
