/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.VhscProdutos;
import bean.VhscProdutos;
import dao.vhsc_ProdutosDAO;
import javax.swing.JOptionPane;
import tools.VHSC_Util;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.util.List;
import dao.vhsc_ProdutosDAO;
import bean.VhscProdutos;


/**
 *
 * @author Vitor
 */
public class VHSC_JDlgProdutos extends javax.swing.JDialog {
    private boolean incluir;
    /**
     * Creates new form VHSC_JDlgProdutos
     */
    public VHSC_JDlgProdutos(java.awt.Frame parent, boolean modal) {
       
        
        super(parent, modal);
        initComponents();
         setTitle("Cadastro de Produtos");
        setLocationRelativeTo(null);
        VHSC_Util.habilitar(false, jTxtAutor, jTxtCodigo, jTxtDescricao,jTxtPreco,jTxtQuantidade,
        jTxtTitulo,jFmtAnoPublicado, jBtnConfirmar,jBtnCancelar);
    }
     public void beanView(VhscProdutos vhscProdutos) {
        jTxtCodigo.setText(VHSC_Util.intToStr(vhscProdutos.getVhscIdProduto()));
        jTxtTitulo.setText(vhscProdutos.getVhscTitulo());
        jTxtAutor.setText(vhscProdutos.getVhscAutor());
        jTxtQuantidade.setText(VHSC_Util.intToStr(vhscProdutos.getVhscQuantidade()));
        jFmtAnoPublicado.setText(VHSC_Util.dateToStr(vhscProdutos.getVhscAnoPublicado()));
        jTxtPreco.setText(VHSC_Util.doubleToStr(vhscProdutos.getVhscPreco()));
        jTxtDescricao.setText(vhscProdutos.getVhscDescricao());
        
       
     }
     public VhscProdutos viewBean() {
    VhscProdutos vhscProdutos = new VhscProdutos();
        int codigo = VHSC_Util.strToInt(jTxtCodigo.getText());
        vhscProdutos.setVhscIdProduto(codigo);
        
    vhscProdutos.setVhscTitulo(jTxtTitulo.getText());
    vhscProdutos.setVhscAutor(jTxtAutor.getText());
    vhscProdutos.setVhscQuantidade(VHSC_Util.strToInt(jTxtQuantidade.getText()));
    vhscProdutos.setVhscAnoPublicado(VHSC_Util.strToDate(jFmtAnoPublicado.getText()));
    vhscProdutos.setVhscPreco(VHSC_Util.strToInt(jTxtQuantidade.getText()));
    vhscProdutos.setVhscDescricao(jTxtDescricao.getText());
    
    
    
    return vhscProdutos;
}
     public void gerarRelatorioPDF() {
    vhsc_ProdutosDAO dao = new vhsc_ProdutosDAO();
    List<VhscProdutos> livros = (List<VhscProdutos>) dao.listAll();

    if (livros.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nenhum livro disponível para gerar relatório.");
        return;
    }

    Document document = new Document();
    try {
        PdfWriter.getInstance(document, new FileOutputStream("Relatorio_Livros.pdf"));
        document.open();
        
        document.add(new Paragraph("Relatório de Livros Disponíveis"));
        document.add(new Paragraph(" "));

        PdfPTable table = new PdfPTable(5); 
        table.addCell("Código");
        table.addCell("Título");
        table.addCell("Autor");
        table.addCell("Ano");
        table.addCell("Quantidade");

        for (VhscProdutos livro : livros) {
            if (livro.getVhscQuantidade() > 0) { 
                table.addCell(String.valueOf(livro.getVhscIdProduto()));
                table.addCell(livro.getVhscTitulo());
                table.addCell(livro.getVhscAutor());
                table.addCell(VHSC_Util.dateToStr(livro.getVhscAnoPublicado()));
                table.addCell(String.valueOf(livro.getVhscQuantidade()));
            }
        }

        document.add(table);
        JOptionPane.showMessageDialog(this, "PDF gerado com sucesso!");

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao gerar PDF: " + e.getMessage());
    } finally {
        document.close();
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jTxtCodigo = new javax.swing.JTextField();
        jTxtDescricao = new javax.swing.JTextField();
        jTxtAutor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFmtAnoPublicado = new javax.swing.JFormattedTextField();
        jTxtQuantidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtPreco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtTitulo = new javax.swing.JTextField();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        JBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnGerarPDF = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoActionPerformed(evt);
            }
        });

        jTxtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDescricaoActionPerformed(evt);
            }
        });

        jLabel5.setText("Descrição");

        try {
            jFmtAnoPublicado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtAnoPublicado.setToolTipText("");

        jTxtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQuantidadeActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo");

        jTxtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPrecoActionPerformed(evt);
            }
        });

        jLabel2.setText("Titulo");

        jLabel3.setText("Autor");

        jLabel6.setText("Quantidade");

        jLabel7.setText("Ano Publicado");

        jLabel8.setText("Preço");

        jTxtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTituloActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        JBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        JBtnAlterar.setText("Alterar");
        JBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnGerarPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-relatório-20.png"))); // NOI18N
        jBtnGerarPDF.setText("Gerar Pdf");
        jBtnGerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGerarPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnGerarPDF))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jTxtCodigo)
                        .addComponent(jTxtTitulo)
                        .addComponent(jTxtAutor)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jFmtAnoPublicado)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jTxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtAnoPublicado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar)
                    .addComponent(JBtnAlterar)
                    .addComponent(jBtnGerarPDF))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoActionPerformed

    private void jTxtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDescricaoActionPerformed

    private void jTxtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQuantidadeActionPerformed

    private void jTxtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPrecoActionPerformed

    private void jTxtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTituloActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        VHSC_JDlgProdutosPesquisar vhsc_JDlgProdutosPesquisar = new VHSC_JDlgProdutosPesquisar(null, true);
        vhsc_JDlgProdutosPesquisar.setTelaAnterior(this);
        vhsc_JDlgProdutosPesquisar.setVisible(true);


    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        VHSC_Util.habilitar(true, jTxtAutor, jTxtCodigo, jTxtDescricao,jTxtPreco,jTxtQuantidade,
        jTxtTitulo,jFmtAnoPublicado, jBtnConfirmar,jBtnCancelar);
        VHSC_Util.habilitar(false, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar);
        VHSC_Util.limpar(  jTxtAutor, jTxtCodigo, jTxtDescricao,jTxtPreco,jTxtQuantidade,
        jTxtTitulo,jFmtAnoPublicado);
        incluir = true;
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void JBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAlterarActionPerformed
        // TODO add your handling code here:
           if (jTxtCodigo.getText().trim().isEmpty()) {
        VHSC_Util.mensagem("Pesquise antes de Alterar.");
        return;
    }
        VHSC_Util.habilitar(true, jTxtAutor, jTxtDescricao,jTxtPreco,jTxtQuantidade,
        jTxtTitulo,jFmtAnoPublicado, jBtnConfirmar,jBtnCancelar);
        VHSC_Util.habilitar(false, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar,jTxtCodigo);
        incluir = false;
    }//GEN-LAST:event_JBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
         if (jTxtCodigo.getText().trim().isEmpty()) {
        VHSC_Util.mensagem("Pesquise antes de Excluir.");
        return;
    }
        if (VHSC_Util.pergunta("Deseja excluir ?") == true) {
            vhsc_ProdutosDAO vhsc_produtosDAO = new vhsc_ProdutosDAO();
            vhsc_produtosDAO.delete(viewBean());
        }
        VHSC_Util.limpar(  jTxtAutor, jTxtCodigo, jTxtDescricao,jTxtPreco,jTxtQuantidade,
        jTxtTitulo,jFmtAnoPublicado);
    
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        
          vhsc_ProdutosDAO vhsc_produtosDAO = new vhsc_ProdutosDAO();
        VhscProdutos vhscProdutos = viewBean();
        if (incluir == true) {
            vhsc_produtosDAO.insert(vhscProdutos);
          
        } else {
            vhsc_produtosDAO.update(vhscProdutos);
            
        }
        VHSC_Util.habilitar(false, jTxtAutor, jTxtCodigo, jTxtDescricao,jTxtPreco,jTxtQuantidade,
        jTxtTitulo,jFmtAnoPublicado, jBtnConfirmar,jBtnCancelar);

        VHSC_Util.habilitar(true, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar);

        VHSC_Util.limpar(  jTxtAutor, jTxtCodigo, jTxtDescricao,jTxtPreco,jTxtQuantidade,
        jTxtTitulo,jFmtAnoPublicado);
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        //desabilitar()
        VHSC_Util.habilitar(false, jTxtAutor, jTxtCodigo, jTxtDescricao,jTxtPreco,jTxtQuantidade,
        jTxtTitulo,jFmtAnoPublicado, jBtnConfirmar,jBtnCancelar);

        VHSC_Util.habilitar(true, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar);

        VHSC_Util.limpar(  jTxtAutor, jTxtCodigo, jTxtDescricao,jTxtPreco,jTxtQuantidade,
        jTxtTitulo,jFmtAnoPublicado);

    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnGerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGerarPDFActionPerformed
        // TODO add your handling code here:
     gerarRelatorioPDF();
    }//GEN-LAST:event_jBtnGerarPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VHSC_JDlgProdutos dialog = new VHSC_JDlgProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnGerarPDF;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFormattedTextField jFmtAnoPublicado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtAutor;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtDescricao;
    private javax.swing.JTextField jTxtPreco;
    private javax.swing.JTextField jTxtQuantidade;
    private javax.swing.JTextField jTxtTitulo;
    // End of variables declaration//GEN-END:variables

    
}
