/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Vitor
 */
public class VHSC_JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VHSC_JFrmPrincipal
     */
    public VHSC_JFrmPrincipal() {
        initComponents();
        setTitle("Loja De Livros");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBtnImgClientes = new javax.swing.JButton();
        jBtnClientes = new javax.swing.JButton();
        jBtnImgFuncionarios = new javax.swing.JButton();
        jBtnFuncionarios = new javax.swing.JButton();
        jBtnImgVendas = new javax.swing.JButton();
        jBtnVendas = new javax.swing.JButton();
        jBtnImgConsultaClient = new javax.swing.JButton();
        jBtnConsultaClientes = new javax.swing.JButton();
        jBtnImgConsultaProd = new javax.swing.JButton();
        jBtnConsultaProdutos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMnuCadastros = new javax.swing.JMenu();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jMnuClientes = new javax.swing.JMenuItem();
        jMnuProdutos = new javax.swing.JMenuItem();
        jMnuFuncionarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuMovimentos = new javax.swing.JMenu();
        jMnuVendas = new javax.swing.JMenuItem();
        jMnuVendas_produtos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMnuConsultasProdutos = new javax.swing.JMenuItem();
        jMnuConsultasVendas = new javax.swing.JMenuItem();
        jMnuConsultasClientes = new javax.swing.JMenuItem();
        jMnuConsultasFuncionarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jBtnImgClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cliente.png"))); // NOI18N
        jBtnImgClientes.setFocusable(false);
        jBtnImgClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnImgClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnImgClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnImgClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnImgClientes);

        jBtnClientes.setText("Clientes");
        jBtnClientes.setFocusable(false);
        jBtnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnClientes);

        jBtnImgFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cupons.png"))); // NOI18N
        jBtnImgFuncionarios.setFocusable(false);
        jBtnImgFuncionarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnImgFuncionarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnImgFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnImgFuncionariosActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnImgFuncionarios);

        jBtnFuncionarios.setText("Funcionarios");
        jBtnFuncionarios.setFocusable(false);
        jBtnFuncionarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnFuncionarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFuncionariosActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnFuncionarios);

        jBtnImgVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vandas.png"))); // NOI18N
        jBtnImgVendas.setFocusable(false);
        jBtnImgVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnImgVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnImgVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnImgVendasActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnImgVendas);

        jBtnVendas.setText("Vendas");
        jBtnVendas.setFocusable(false);
        jBtnVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVendasActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnVendas);

        jBtnImgConsultaClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Usuarios.png"))); // NOI18N
        jBtnImgConsultaClient.setFocusable(false);
        jBtnImgConsultaClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnImgConsultaClient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnImgConsultaClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnImgConsultaClientActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnImgConsultaClient);

        jBtnConsultaClientes.setText("Consulta Clientes");
        jBtnConsultaClientes.setFocusable(false);
        jBtnConsultaClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnConsultaClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultaClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnConsultaClientes);

        jBtnImgConsultaProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produtos.png"))); // NOI18N
        jBtnImgConsultaProd.setFocusable(false);
        jBtnImgConsultaProd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnImgConsultaProd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnImgConsultaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnImgConsultaProdActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnImgConsultaProd);

        jBtnConsultaProdutos.setText("Consulta Produtos");
        jBtnConsultaProdutos.setFocusable(false);
        jBtnConsultaProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnConsultaProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnConsultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultaProdutosActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnConsultaProdutos);

        JMnuCadastros.setText("Cadastros");
        JMnuCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMnuCadastrosActionPerformed(evt);
            }
        });

        jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Usuarios.png"))); // NOI18N
        jMnuUsuarios.setMnemonic('U');
        jMnuUsuarios.setText("Usuarios");
        jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosActionPerformed(evt);
            }
        });
        JMnuCadastros.add(jMnuUsuarios);

        jMnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cliente.png"))); // NOI18N
        jMnuClientes.setMnemonic('C');
        jMnuClientes.setText("Clientes");
        jMnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientesActionPerformed(evt);
            }
        });
        JMnuCadastros.add(jMnuClientes);

        jMnuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto.png"))); // NOI18N
        jMnuProdutos.setMnemonic('P');
        jMnuProdutos.setText("Produtos");
        jMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutosActionPerformed(evt);
            }
        });
        JMnuCadastros.add(jMnuProdutos);

        jMnuFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMnuFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cupons.png"))); // NOI18N
        jMnuFuncionarios.setMnemonic('F');
        jMnuFuncionarios.setText("Funcionarios");
        jMnuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFuncionariosActionPerformed(evt);
            }
        });
        JMnuCadastros.add(jMnuFuncionarios);
        JMnuCadastros.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        jMnuSair.setMnemonic('S');
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        JMnuCadastros.add(jMnuSair);

        jMenuBar1.add(JMnuCadastros);

        jMnuMovimentos.setMnemonic('V');
        jMnuMovimentos.setText("Movimentos");

        jMnuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vandas.png"))); // NOI18N
        jMnuVendas.setMnemonic('v');
        jMnuVendas.setText("Vendas");
        jMnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendasActionPerformed(evt);
            }
        });
        jMnuMovimentos.add(jMnuVendas);

        jMnuVendas_produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas_produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produtos.png"))); // NOI18N
        jMnuVendas_produtos.setMnemonic('V');
        jMnuVendas_produtos.setText("Vendas_produtos");
        jMnuVendas_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendas_produtosActionPerformed(evt);
            }
        });
        jMnuMovimentos.add(jMnuVendas_produtos);

        jMenuBar1.add(jMnuMovimentos);

        jMenu1.setText("Consultas");

        jMnuConsultasProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultasProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-box-20.png"))); // NOI18N
        jMnuConsultasProdutos.setMnemonic('p');
        jMnuConsultasProdutos.setText("Produtos");
        jMnuConsultasProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultasProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuConsultasProdutos);

        jMnuConsultasVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultasVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-sales-performance-20.png"))); // NOI18N
        jMnuConsultasVendas.setMnemonic('p');
        jMnuConsultasVendas.setText("Vendas");
        jMnuConsultasVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultasVendasActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuConsultasVendas);

        jMnuConsultasClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultasClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-users-20.png"))); // NOI18N
        jMnuConsultasClientes.setMnemonic('p');
        jMnuConsultasClientes.setText("Clientes");
        jMnuConsultasClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultasClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuConsultasClientes);

        jMnuConsultasFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultasFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-lawyers-20.png"))); // NOI18N
        jMnuConsultasFuncionarios.setMnemonic('p');
        jMnuConsultasFuncionarios.setText("Funcionarios");
        jMnuConsultasFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultasFuncionariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuConsultasFuncionarios);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 248, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
        // TODO add your handling code here:
        new VHSC_JDlgUsuarios(this, rootPaneCheckingEnabled).setVisible(true);

    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void jMnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientesActionPerformed
        // TODO add your handling code here:
        new VHSC_JDlgClientes(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMnuClientesActionPerformed

    private void jMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutosActionPerformed
        // TODO add your handling code here:
        new VHSC_JDlgProdutos(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMnuProdutosActionPerformed

    private void jMnuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFuncionariosActionPerformed
        // TODO add your handling code here:
        new VHSC_JDlgFuncionarios(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMnuFuncionariosActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        dispose();
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void JMnuCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMnuCadastrosActionPerformed

    }//GEN-LAST:event_JMnuCadastrosActionPerformed

    private void jMnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendasActionPerformed
       new VHSC_JDlgVendas(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMnuVendasActionPerformed

    private void jMnuVendas_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendas_produtosActionPerformed
        // TODO add your handling code here:
         new VHSC_JDlgVendasProdutos(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMnuVendas_produtosActionPerformed

    private void jMnuConsultasProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultasProdutosActionPerformed
        new VHSC_JDlgConsultaProdutos(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMnuConsultasProdutosActionPerformed

    private void jMnuConsultasVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultasVendasActionPerformed
       new VHSC_JDlgConsultaVendas(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMnuConsultasVendasActionPerformed

    private void jMnuConsultasClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultasClientesActionPerformed
        new VHSC_JDlgConsultaClientes(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMnuConsultasClientesActionPerformed

    private void jMnuConsultasFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultasFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuConsultasFuncionariosActionPerformed

    private void jBtnImgClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnImgClientesActionPerformed
        new VHSC_JDlgClientes(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jBtnImgClientesActionPerformed

    private void jBtnImgFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnImgFuncionariosActionPerformed
         new VHSC_JDlgFuncionarios(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jBtnImgFuncionariosActionPerformed

    private void jBtnImgVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnImgVendasActionPerformed
         new VHSC_JDlgVendas(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jBtnImgVendasActionPerformed

    private void jBtnImgConsultaClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnImgConsultaClientActionPerformed
         new VHSC_JDlgConsultaClientes(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jBtnImgConsultaClientActionPerformed

    private void jBtnImgConsultaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnImgConsultaProdActionPerformed
         new VHSC_JDlgConsultaProdutos(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jBtnImgConsultaProdActionPerformed

    private void jBtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClientesActionPerformed
        // TODO add your handling code here:
         new VHSC_JDlgClientes(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jBtnClientesActionPerformed

    private void jBtnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFuncionariosActionPerformed
       new VHSC_JDlgFuncionarios(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jBtnFuncionariosActionPerformed

    private void jBtnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVendasActionPerformed
        new VHSC_JDlgVendas(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jBtnVendasActionPerformed

    private void jBtnConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultaClientesActionPerformed
         new VHSC_JDlgConsultaClientes(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jBtnConsultaClientesActionPerformed

    private void jBtnConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultaProdutosActionPerformed
         new VHSC_JDlgConsultaProdutos(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jBtnConsultaProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VHSC_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VHSC_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VHSC_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VHSC_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VHSC_JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMnuCadastros;
    private javax.swing.JButton jBtnClientes;
    private javax.swing.JButton jBtnConsultaClientes;
    private javax.swing.JButton jBtnConsultaProdutos;
    private javax.swing.JButton jBtnFuncionarios;
    private javax.swing.JButton jBtnImgClientes;
    private javax.swing.JButton jBtnImgConsultaClient;
    private javax.swing.JButton jBtnImgConsultaProd;
    private javax.swing.JButton jBtnImgFuncionarios;
    private javax.swing.JButton jBtnImgVendas;
    private javax.swing.JButton jBtnVendas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnuClientes;
    private javax.swing.JMenuItem jMnuConsultasClientes;
    private javax.swing.JMenuItem jMnuConsultasFuncionarios;
    private javax.swing.JMenuItem jMnuConsultasProdutos;
    private javax.swing.JMenuItem jMnuConsultasVendas;
    private javax.swing.JMenuItem jMnuFuncionarios;
    private javax.swing.JMenu jMnuMovimentos;
    private javax.swing.JMenuItem jMnuProdutos;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JMenuItem jMnuVendas;
    private javax.swing.JMenuItem jMnuVendas_produtos;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
