/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;



import bean.VhscClientes;
import bean.VhscProdutos;
import bean.VhscVendas;
import view.VHSC_JDlgVendas;

import java.util.List;
import bean.VhscVendasProdutos;
import dao.vhsc_ProdutosDAO;

import tools.VHSC_Util;
/**
 *
 * @author Vitor
 */
public class VHSC_JDlgVendasProdutos extends javax.swing.JDialog {
VHSC_JDlgVendas VHSC_jDlgVendas;
boolean incluir;
    /**
     * Creates new form VHSC_JDlgVendasProdutos
     */
    public VHSC_JDlgVendasProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Vendas produtos");
        setLocationRelativeTo(null);
         VHSC_jTxtQuantidade.setText("1");
        vhsc_ProdutosDAO vhsc_produtosDAO = new vhsc_ProdutosDAO();
        List lista = (List) vhsc_produtosDAO.listAll();
        for (Object object : lista) {
            VHSC_jCboProdutos.addItem((VhscProdutos) object);
        }
        VHSC_Util.habilitar(false, VHSC_jTxtPrecoUnitario, VHSC_jTxtTotal);
       
    }
    
    public void setTelaAnterior(VHSC_JDlgVendas Vhsc_jDlgVendas, VhscVendasProdutos vhscVendasProdutos) {
        this.VHSC_jDlgVendas = Vhsc_jDlgVendas;
 
        if (vhscVendasProdutos != null) {
            incluir = false;
            VHSC_jCboProdutos.setSelectedItem(vhscVendasProdutos.getVhscProdutos());
            VHSC_jTxtQuantidade.setText(VHSC_Util.intToStr(vhscVendasProdutos.getVhscQuantidade()));        
        } else {
            incluir = true;
        
    }
      
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        VHSC_jCboProdutos = new javax.swing.JComboBox<VhscProdutos>();
        jLabel2 = new javax.swing.JLabel();
        VHSC_jTxtQuantidade = new javax.swing.JTextField();
        VHSC_jTxtPrecoUnitario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        VHSC_jTxtTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Produtos");

        VHSC_jCboProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jCboProdutosActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade");

        VHSC_jTxtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jTxtQuantidadeActionPerformed(evt);
            }
        });

        VHSC_jTxtPrecoUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VHSC_jTxtPrecoUnitarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor Unitário");

        jLabel4.setText("Total");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(VHSC_jCboProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(40, 40, 40)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(VHSC_jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VHSC_jTxtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VHSC_jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VHSC_jTxtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VHSC_jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VHSC_jCboProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VHSC_jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VhscVendasProdutos vhscVendasProdutos = new VhscVendasProdutos();
        vhscVendasProdutos.setVhscProdutos((VhscProdutos) VHSC_jCboProdutos.getSelectedItem());
        vhscVendasProdutos.setVhscQuantidade(VHSC_Util.strToInt(VHSC_jTxtQuantidade.getText()) );
        vhscVendasProdutos.setVhscPrecoUnitario(VHSC_Util.strToDouble(VHSC_jTxtPrecoUnitario.getText()) ); 
          if (incluir == true) {
           VHSC_jDlgVendas.controllerVendasProd.addBean(vhscVendasProdutos);
        } else {
            VHSC_jDlgVendas.controllerVendasProd.removeBean(VHSC_jDlgVendas.getjTable1().getSelectedRow());
           VHSC_jDlgVendas.controllerVendasProd.addBean(vhscVendasProdutos);
        }
       
        setVisible(false); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VHSC_jTxtPrecoUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jTxtPrecoUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VHSC_jTxtPrecoUnitarioActionPerformed

    private void VHSC_jCboProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jCboProdutosActionPerformed
        // TODO add your handling code here:
        VhscProdutos vhscProdutos = (VhscProdutos) VHSC_jCboProdutos.getSelectedItem();
        VHSC_jTxtPrecoUnitario.setText(VHSC_Util.doubleToStr(vhscProdutos.getVhscPreco()));
        int quant = VHSC_Util.strToInt(VHSC_jTxtQuantidade.getText());
        VHSC_jTxtTotal.setText(VHSC_Util.doubleToStr( quant * vhscProdutos.getVhscPreco()));
    }//GEN-LAST:event_VHSC_jCboProdutosActionPerformed

    private void VHSC_jTxtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VHSC_jTxtQuantidadeActionPerformed
        // TODO add your handling code here:
        if(VHSC_jTxtQuantidade.getText().isEmpty() == false){
        VhscProdutos vhscProdutos = (VhscProdutos) VHSC_jCboProdutos.getSelectedItem();
        int quant = VHSC_Util.strToInt(VHSC_jTxtQuantidade.getText());
        VHSC_jTxtTotal.setText(VHSC_Util.doubleToStr( quant * vhscProdutos.getVhscPreco()));
       } else {
           VHSC_Util.limpar(VHSC_jTxtTotal);
       }
    }//GEN-LAST:event_VHSC_jTxtQuantidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VHSC_JDlgVendasProdutos dialog = new VHSC_JDlgVendasProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<VhscProdutos> VHSC_jCboProdutos;
    private javax.swing.JTextField VHSC_jTxtPrecoUnitario;
    private javax.swing.JTextField VHSC_jTxtQuantidade;
    private javax.swing.JTextField VHSC_jTxtTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
