/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.VhscVendas;
import dao.vhsc_VendasDAO;
import javax.swing.JOptionPane;
import tools.VHSC_Util;

/**
 *
 * @author Vitor
 */
public class VHSC_JDlgVendas extends javax.swing.JDialog {

    /**
     * Creates new form VHSC_JDlgVendas
     */
   private boolean incluir;

    /**
     * Creates new form VHSC_JDlgVendas
     */
    public VHSC_JDlgVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Vendas");
        setLocationRelativeTo(null);
        VHSC_Util.habilitar(false, jTxtValorTotal, jTxtCodigo, jFmtDataVenda,jTxtFormaPagamento,
     jTxtNomeCliente,jTxtNomeProduto, jTxtQuantidade, jBtnConfirmar,jBtnCancelar);
    }
     public void beanView(VhscVendas vhscVendas) {
        jTxtCodigo.setText(VHSC_Util.intToStr(vhscVendas.getVhscIdVenda()));
        jTxtValorTotal.setText(VHSC_Util.doubleToStr(vhscVendas.getVhscValorTotal()));
        jTxtFormaPagamento.setText(vhscVendas.getVhscFormaPagamento());
        jFmtDataVenda.setText(VHSC_Util.dateToStr(vhscVendas.getVhscDataVenda()));
        jTxtQuantidade.setText(VHSC_Util.intToStr(vhscVendas.getVhscQuantidade()));
        jTxtNomeCliente.setText(vhscVendas.getVhscNomeCliente());
        jTxtNomeProduto.setText(vhscVendas.getVhscNomeLivro());
        
      
     }
     public VhscVendas viewBean() {
    VhscVendas vhscVendas = new VhscVendas();
        int codigo = VHSC_Util.strToInt(jTxtCodigo.getText());
        vhscVendas.setVhscIdVenda(codigo);
        
    vhscVendas.setVhscQuantidade(VHSC_Util.strToInt(jTxtQuantidade.getText()));
    vhscVendas.setVhscNomeCliente(jTxtNomeCliente.getText());
    vhscVendas.setVhscNomeLivro(jTxtNomeProduto.getText());
    vhscVendas.setVhscDataVenda(VHSC_Util.strToDate(jFmtDataVenda.getText()));
    vhscVendas.setVhscFormaPagamento(jTxtFormaPagamento.getText());
    vhscVendas.setVhscValorTotal(VHSC_Util.strToDouble(jTxtValorTotal.getText()));
   
    
    return vhscVendas;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jBtnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jBtnPesquisar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jFmtDataVenda = new javax.swing.JFormattedTextField();
        jTxtQuantidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtFormaPagamento = new javax.swing.JTextField();
        JBtnIncluir2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JBtnAlterar2 = new javax.swing.JButton();
        jTxtCodigo = new javax.swing.JTextField();
        jBtnExcluir2 = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        JBtnAlterar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBtnExcluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTxtValorTotal = new javax.swing.JTextField();
        jBtnConfirmar = new javax.swing.JButton();
        jTxtNomeCliente = new javax.swing.JFormattedTextField();
        jTxtNomeProduto = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Data venda");

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("Quantidade");

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor total");

        jFmtDataVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDataVendaActionPerformed(evt);
            }
        });

        jTxtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQuantidadeActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente");

        JBtnIncluir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        JBtnIncluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnIncluir2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Num vendas");

        JBtnAlterar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        JBtnAlterar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAlterar2ActionPerformed(evt);
            }
        });

        jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoActionPerformed(evt);
            }
        });

        jBtnExcluir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir2ActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        JBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        JBtnAlterar.setText("Alterar");
        JBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAlterarActionPerformed(evt);
            }
        });

        jLabel4.setText("FormaPagamento");

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jLabel7.setText("Produto");

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jTxtNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeClienteActionPerformed(evt);
            }
        });

        jTxtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jFmtDataVenda))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTxtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtFormaPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnExcluir)
                        .addGap(21, 21, 21)
                        .addComponent(jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnPesquisar)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBtnAlterar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBtnIncluir2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnExcluir2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFmtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTxtFormaPagamento))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(JBtnIncluir2)
                        .addGap(14, 14, 14)
                        .addComponent(JBtnAlterar2)
                        .addGap(15, 15, 15)
                        .addComponent(jBtnExcluir2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnIncluir)
                        .addComponent(jBtnExcluir)
                        .addComponent(jBtnConfirmar)
                        .addComponent(jBtnCancelar)
                        .addComponent(JBtnAlterar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        //desabilita  //desabilitar()
        VHSC_Util.habilitar(false, jTxtValorTotal, jTxtCodigo, jFmtDataVenda,jTxtFormaPagamento,
        jTxtNomeCliente,jTxtNomeProduto,jTxtQuantidade, jBtnConfirmar,jBtnCancelar);
       
         VHSC_Util.habilitar(true, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar);
         
              VHSC_Util.limpar(  jTxtValorTotal, jTxtCodigo, jFmtDataVenda,jTxtFormaPagamento,
        jTxtNomeCliente,jTxtNomeProduto,jTxtQuantidade);
      
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
         VHSC_JDlgVendasPesquisar vhsc_JDlgVendasPesquisar = new VHSC_JDlgVendasPesquisar(null, true);
         vhsc_JDlgVendasPesquisar.setTelaAnterior(this);
         vhsc_JDlgVendasPesquisar.setVisible(true);

    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jFmtDataVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDataVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtDataVendaActionPerformed

    private void jTxtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQuantidadeActionPerformed
  
    }//GEN-LAST:event_jTxtQuantidadeActionPerformed

    private void JBtnIncluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnIncluir2ActionPerformed
        // TODO add your handling code here:
        VHSC_Util.habilitar(true, jTxtValorTotal, jTxtCodigo, jFmtDataVenda,jTxtFormaPagamento,
        jTxtNomeCliente,jTxtNomeProduto,jTxtQuantidade, jBtnConfirmar,jBtnCancelar);
         VHSC_Util.habilitar(false, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar);
         VHSC_Util.limpar( jTxtValorTotal, jTxtCodigo, jFmtDataVenda,jTxtFormaPagamento,
        jTxtNomeCliente,jTxtNomeProduto, jTxtQuantidade);
         incluir = true;
    }//GEN-LAST:event_JBtnIncluir2ActionPerformed

    private void JBtnAlterar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAlterar2ActionPerformed
  if (jTxtCodigo.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Pesquise um usuário antes de alterar.");
        return;
    }
        VHSC_Util.habilitar(true, jTxtValorTotal, jFmtDataVenda,jTxtFormaPagamento,
        jTxtNomeCliente,jTxtNomeProduto,jTxtQuantidade, jBtnConfirmar,jBtnCancelar);
         VHSC_Util.habilitar(false, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar, jTxtCodigo);
         incluir = false;        // TODO add your handling code here:

    }//GEN-LAST:event_JBtnAlterar2ActionPerformed

    private void jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoActionPerformed

    private void jBtnExcluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir2ActionPerformed
  if (VHSC_Util.pergunta("Deseja excluir ?") == true) {
            vhsc_VendasDAO vhsc_vendasDAO = new vhsc_VendasDAO();
            vhsc_vendasDAO.delete(viewBean());
        }
        VHSC_Util.limpar( jTxtValorTotal, jTxtCodigo, jFmtDataVenda,jTxtFormaPagamento,
        jTxtNomeCliente, jTxtQuantidade);        // TODO add your handling code here:

    }//GEN-LAST:event_jBtnExcluir2ActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        VHSC_Util.habilitar(true, jTxtValorTotal, jTxtCodigo, jFmtDataVenda,jTxtFormaPagamento,
        jTxtNomeCliente,jTxtNomeProduto,jTxtQuantidade, jBtnConfirmar,jBtnCancelar);
         VHSC_Util.habilitar(false, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar);
         VHSC_Util.limpar( jTxtValorTotal, jTxtCodigo, jFmtDataVenda,jTxtFormaPagamento,
        jTxtNomeCliente,jTxtNomeProduto, jTxtQuantidade);
         incluir = true;
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void JBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAlterarActionPerformed
        // TODO add your handling code here:
 // TODO add your handling code here:
         if (jTxtCodigo.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Pesquise um usuário antes de alterar.");
        return;
    }
       
         VHSC_Util.habilitar(true, jTxtValorTotal, jFmtDataVenda,jTxtFormaPagamento,
        jTxtNomeCliente,jTxtNomeProduto,jTxtQuantidade, jBtnConfirmar,jBtnCancelar);
         VHSC_Util.habilitar(false, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar, jTxtCodigo);
         incluir = false;
    }//GEN-LAST:event_JBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
      if (VHSC_Util.pergunta("Deseja excluir ?") == true) {
            vhsc_VendasDAO vhsc_vendasDAO = new vhsc_VendasDAO();
            vhsc_vendasDAO.delete(viewBean());
        }
        VHSC_Util.limpar( jTxtValorTotal, jTxtCodigo, jFmtDataVenda,jTxtFormaPagamento,
        jTxtNomeCliente,jTxtNomeProduto, jTxtQuantidade);
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        //desabilitar();
     //desabilitar();
          vhsc_VendasDAO vhsc_vendasDAO = new vhsc_VendasDAO();
        VhscVendas vhscVendas = viewBean();
        if (incluir == true) {
            vhsc_vendasDAO.insert(vhscVendas);
            //vendasDAO.insert( viewBean() );
        } else {
            vhsc_vendasDAO.update(vhscVendas);
            //vendasDAO.update( viewBean() );
        }
        
       VHSC_Util.habilitar(false, jTxtValorTotal, jTxtCodigo, jFmtDataVenda,jTxtFormaPagamento,
        jTxtNomeCliente,jTxtNomeProduto,jTxtQuantidade, jBtnConfirmar,jTxtQuantidade, jBtnCancelar);
       
         VHSC_Util.habilitar(true, jBtnIncluir, JBtnAlterar, jBtnExcluir, jBtnPesquisar);
         
              VHSC_Util.limpar(  jTxtValorTotal, jTxtCodigo, jFmtDataVenda,jTxtFormaPagamento,
        jTxtNomeCliente,jTxtNomeProduto, jTxtQuantidade);

    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jTxtNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeClienteActionPerformed

    private void jTxtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VHSC_JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VHSC_JDlgVendas dialog = new VHSC_JDlgVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAlterar;
    private javax.swing.JButton JBtnAlterar2;
    private javax.swing.JButton JBtnIncluir2;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnExcluir2;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JFormattedTextField jFmtDataVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtFormaPagamento;
    private javax.swing.JFormattedTextField jTxtNomeCliente;
    private javax.swing.JFormattedTextField jTxtNomeProduto;
    private javax.swing.JTextField jTxtQuantidade;
    private javax.swing.JTextField jTxtValorTotal;
    // End of variables declaration//GEN-END:variables
}
