package bean;
// Generated 12/10/2025 22:26:10 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VhscProdutos generated by hbm2java
 */
@Entity
@Table(name="vhsc_produtos"
    ,catalog="db_vitor_carvalho"
)
public class VhscProdutos  implements java.io.Serializable {


     private int vhscIdProduto;
     private String vhscTitulo;
     private String vhscAutor;
     private double vhscPreco;
     private int vhscQuantidade;
     private String vhscDescricao;
     private Date vhscAnoPublicado;
     

    public VhscProdutos() {
    }

	
    public VhscProdutos(int vhscIdProduto, String vhscTitulo, String vhscAutor, double vhscPreco, int vhscQuantidade, String vhscDescricao, Date vhscAnoPublicado) {
        this.vhscIdProduto = vhscIdProduto;
        this.vhscTitulo = vhscTitulo;
        this.vhscAutor = vhscAutor;
        this.vhscPreco = vhscPreco;
        this.vhscQuantidade = vhscQuantidade;
        this.vhscDescricao = vhscDescricao;
        this.vhscAnoPublicado = vhscAnoPublicado;
    }
    public VhscProdutos(int vhscIdProduto, String vhscTitulo, String vhscAutor, double vhscPreco, int vhscQuantidade, String vhscDescricao, Date vhscAnoPublicado, Set vhscVendasProdutoses) {
       this.vhscIdProduto = vhscIdProduto;
       this.vhscTitulo = vhscTitulo;
       this.vhscAutor = vhscAutor;
       this.vhscPreco = vhscPreco;
       this.vhscQuantidade = vhscQuantidade;
       this.vhscDescricao = vhscDescricao;
       this.vhscAnoPublicado = vhscAnoPublicado;
   
    }
   
     @Id 

    
    @Column(name="VHSC_idProduto", unique=true, nullable=false)
    public int getVhscIdProduto() {
        return this.vhscIdProduto;
    }
    
    public void setVhscIdProduto(int vhscIdProduto) {
        this.vhscIdProduto = vhscIdProduto;
    }

    
    @Column(name="VHSC_titulo", nullable=false, length=150)
    public String getVhscTitulo() {
        return this.vhscTitulo;
    }
    
    public void setVhscTitulo(String vhscTitulo) {
        this.vhscTitulo = vhscTitulo;
    }

    
    @Column(name="VHSC_autor", nullable=false, length=100)
    public String getVhscAutor() {
        return this.vhscAutor;
    }
    
    public void setVhscAutor(String vhscAutor) {
        this.vhscAutor = vhscAutor;
    }

    
    @Column(name="VHSC_preco", nullable=false, precision=10)
    public double getVhscPreco() {
        return this.vhscPreco;
    }
    
    public void setVhscPreco(double vhscPreco) {
        this.vhscPreco = vhscPreco;
    }

    
    @Column(name="VHSC_quantidade", nullable=false)
    public int getVhscQuantidade() {
        return this.vhscQuantidade;
    }
    
    public void setVhscQuantidade(int vhscQuantidade) {
        this.vhscQuantidade = vhscQuantidade;
    }

    
    @Column(name="VHSC_descricao", nullable=false, length=100)
    public String getVhscDescricao() {
        return this.vhscDescricao;
    }
    
    public void setVhscDescricao(String vhscDescricao) {
        this.vhscDescricao = vhscDescricao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VHSC_anoPublicado",length=10)
    public Date getVhscAnoPublicado() {
        return this.vhscAnoPublicado;
    }
    
    public void setVhscAnoPublicado(Date vhscAnoPublicado) {
        this.vhscAnoPublicado = vhscAnoPublicado;
    }


@Override
public String toString() {
    return this.vhscTitulo;
}



}


