package bean;
// Generated 12/10/2025 22:26:10 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VhscUsuarios generated by hbm2java
 */
@Entity
@Table(name="VHSC_Usuarios"
    ,catalog="db_vitor_carvalho"
)
public class VhscUsuarios  implements java.io.Serializable {


     private int vhscIdUsuario;
     private String vhscNomeUsuario;
     private String vhscApelido;
     private Date vhscDataNascimento;
     private String vhscCpf;
     private String vhscSenha;
     private int vhscNivel;
     private String vhscAtivo;

    public VhscUsuarios() {
    }

    public VhscUsuarios(int vhscIdUsuario, String vhscNomeUsuario, String vhscApelido, Date vhscDataNascimento, String vhscCpf, String vhscSenha, int vhscNivel, String vhscAtivo) {
       this.vhscIdUsuario = vhscIdUsuario;
       this.vhscNomeUsuario = vhscNomeUsuario;
       this.vhscApelido = vhscApelido;
       this.vhscDataNascimento = vhscDataNascimento;
       this.vhscCpf = vhscCpf;
       this.vhscSenha = vhscSenha;
       this.vhscNivel = vhscNivel;
       this.vhscAtivo = vhscAtivo;
    }
   
     @Id 

    
    @Column(name="VHSC_idUsuario", unique=true, nullable=false)
    public int getVhscIdUsuario() {
        return this.vhscIdUsuario;
    }
    
    public void setVhscIdUsuario(int vhscIdUsuario) {
        this.vhscIdUsuario = vhscIdUsuario;
    }

    
    @Column(name="VHSC_nomeUsuario", nullable=false, length=50)
    public String getVhscNomeUsuario() {
        return this.vhscNomeUsuario;
    }
    
    public void setVhscNomeUsuario(String vhscNomeUsuario) {
        this.vhscNomeUsuario = vhscNomeUsuario;
    }

    
    @Column(name="VHSC_apelido", nullable=false, length=50)
    public String getVhscApelido() {
        return this.vhscApelido;
    }
    
    public void setVhscApelido(String vhscApelido) {
        this.vhscApelido = vhscApelido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VHSC_dataNascimento", length=10)
    public Date getVhscDataNascimento() {
        return this.vhscDataNascimento;
    }
    
    public void setVhscDataNascimento(Date vhscDataNascimento) {
        this.vhscDataNascimento = vhscDataNascimento;
    }

    
    @Column(name="VHSC_cpf", nullable=false, length=80)
    public String getVhscCpf() {
        return this.vhscCpf;
    }
    
    public void setVhscCpf(String vhscCpf) {
        this.vhscCpf = vhscCpf;
    }

    
    @Column(name="VHSC_senha", nullable=false, length=100)
    public String getVhscSenha() {
        return this.vhscSenha;
    }
    
    public void setVhscSenha(String vhscSenha) {
        this.vhscSenha = vhscSenha;
    }

    
    @Column(name="VHSC_nivel", nullable=false, length=1)
    public int getVhscNivel() {
        return this.vhscNivel;
    }
    
    public void setVhscNivel(int vhscNivel) {
        this.vhscNivel = vhscNivel;
    }

    
    @Column(name="VHSC_ativo", nullable=false, length=1)
    public String getVhscAtivo() {
        return this.vhscAtivo;
    }
    
    public void setVhscAtivo(String vhscAtivo) {
        this.vhscAtivo = vhscAtivo;
    }




}


