package bean;
// Generated 12/10/2025 22:26:10 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VhscClientes generated by hbm2java
 */
@Entity
@Table(name="vhsc_clientes"
    ,catalog="db_vitor_carvalho"
)
public class VhscClientes  implements java.io.Serializable {


     private int vhscIdCliente;
     private String vhscNome;
     private String vhscCpf;
     private Date vhscDataNascimento;
     private String vhscEmail;
     private String vhscTelefone;
     private String vhscEndereco;
     private String vhscCidade;
     private String vhscEstado;
     private String vhscCep;
     private Date vhscDataCadastro;
     private String vhscAtivo;
     private int vhscGenero;
     private String vhscRendaMensal;
     private String vhscObservacoes;

    public VhscClientes() {
    }

    public VhscClientes(int vhscIdCliente, String vhscNome, String vhscCpf, Date vhscDataNascimento, String vhscEmail, String vhscTelefone, String vhscEndereco, String vhscCidade, String vhscEstado, String vhscCep, Date vhscDataCadastro, String vhscAtivo, int vhscGenero, String vhscRendaMensal, String vhscObservacoes) {
       this.vhscIdCliente = vhscIdCliente;
       this.vhscNome = vhscNome;
       this.vhscCpf = vhscCpf;
       this.vhscDataNascimento = vhscDataNascimento;
       this.vhscEmail = vhscEmail;
       this.vhscTelefone = vhscTelefone;
       this.vhscEndereco = vhscEndereco;
       this.vhscCidade = vhscCidade;
       this.vhscEstado = vhscEstado;
       this.vhscCep = vhscCep;
       this.vhscDataCadastro = vhscDataCadastro;
       this.vhscAtivo = vhscAtivo;
       this.vhscGenero = vhscGenero;
       this.vhscRendaMensal = vhscRendaMensal;
       this.vhscObservacoes = vhscObservacoes;
    }
   
     @Id 

    
    @Column(name="VHSC_idCliente", unique=true, nullable=false)
    public int getVhscIdCliente() {
        return this.vhscIdCliente;
    }
    
    public void setVhscIdCliente(int vhscIdCliente) {
        this.vhscIdCliente = vhscIdCliente;
    }

    
    @Column(name="VHSC_nome", nullable=false, length=100)
    public String getVhscNome() {
        return this.vhscNome;
    }
    
    public void setVhscNome(String vhscNome) {
        this.vhscNome = vhscNome;
    }

    
    @Column(name="VHSC_cpf", nullable=false, length=14)
    public String getVhscCpf() {
        return this.vhscCpf;
    }
    
    public void setVhscCpf(String vhscCpf) {
        this.vhscCpf = vhscCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VHSC_dataNascimento", length=10)
    public Date getVhscDataNascimento() {
        return this.vhscDataNascimento;
    }
    
    public void setVhscDataNascimento(Date vhscDataNascimento) {
        this.vhscDataNascimento = vhscDataNascimento;
    }

    
    @Column(name="VHSC_email", nullable=false, length=80)
    public String getVhscEmail() {
        return this.vhscEmail;
    }
    
    public void setVhscEmail(String vhscEmail) {
        this.vhscEmail = vhscEmail;
    }

    
    @Column(name="VHSC_telefone", nullable=false, length=15)
    public String getVhscTelefone() {
        return this.vhscTelefone;
    }
    
    public void setVhscTelefone(String vhscTelefone) {
        this.vhscTelefone = vhscTelefone;
    }

    
    @Column(name="VHSC_endereco", nullable=false, length=150)
    public String getVhscEndereco() {
        return this.vhscEndereco;
    }
    
    public void setVhscEndereco(String vhscEndereco) {
        this.vhscEndereco = vhscEndereco;
    }

    
    @Column(name="VHSC_cidade", nullable=false, length=50)
    public String getVhscCidade() {
        return this.vhscCidade;
    }
    
    public void setVhscCidade(String vhscCidade) {
        this.vhscCidade = vhscCidade;
    }

    
    @Column(name="VHSC_estado", nullable=false, length=2)
    public String getVhscEstado() {
        return this.vhscEstado;
    }
    
    public void setVhscEstado(String vhscEstado) {
        this.vhscEstado = vhscEstado;
    }

    
    @Column(name="VHSC_cep", nullable=false, length=9)
    public String getVhscCep() {
        return this.vhscCep;
    }
    
    public void setVhscCep(String vhscCep) {
        this.vhscCep = vhscCep;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VHSC_dataCadastro", length=10)
    public Date getVhscDataCadastro() {
        return this.vhscDataCadastro;
    }
    
    public void setVhscDataCadastro(Date vhscDataCadastro) {
        this.vhscDataCadastro = vhscDataCadastro;
    }

    
    @Column(name="VHSC_ativo", nullable=false, length=1)
    public String getVhscAtivo() {
        return this.vhscAtivo;
    }
    
    public void setVhscAtivo(String vhscAtivo) {
        this.vhscAtivo = vhscAtivo;
    }

    
    @Column(name="VHSC_genero", nullable=false, length=1)
    public int getVhscGenero() {
        return this.vhscGenero;
    }
    
    public void setVhscGenero(int vhscGenero) {
        this.vhscGenero = vhscGenero;
    }

    
    @Column(name="VHSC_rendaMensal", nullable=false, length=100)
    public String getVhscRendaMensal() {
        return this.vhscRendaMensal;
    }
    
    public void setVhscRendaMensal(String vhscRendaMensal) {
        this.vhscRendaMensal = vhscRendaMensal;
    }

    
    @Column(name="VHSC_observacoes", nullable=false, length=100)
    public String getVhscObservacoes() {
        return this.vhscObservacoes;
    }
    
    public void setVhscObservacoes(String vhscObservacoes) {
        this.vhscObservacoes = vhscObservacoes;
    }


@Override
    public String toString() {
        return this.vhscIdCliente+ " - " + this.vhscNome;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof VhscClientes) {
            VhscClientes vhscClientes = (VhscClientes) object;
            if (vhscClientes.getVhscIdCliente()== this.getVhscIdCliente()) {
                return true;
            }
        }
        return false;

    }

}


