package bean;
// Generated 12/10/2025 22:26:10 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VhscFuncionarios generated by hbm2java
 */
@Entity
@Table(name="VHSC_Funcionarios"
    ,catalog="vitor_carvalho"
)
public class VhscFuncionarios  implements java.io.Serializable {


     private int vhscIdFuncionario;
     private String vhscNome;
     private String vhscCpf;
     private Date vhscDataNascimento;
     private String vhscEmail;
     private String vhscTelefone;
     private String vhscCargo;
     private String vhscSalario;

    public VhscFuncionarios() {
    }

    public VhscFuncionarios( int vhscIdFuncionario ,String vhscNome, String vhscCpf, Date vhscDataNascimento, String vhscEmail, String vhscTelefone, String vhscCargo, String vhscSalario) {
       this.vhscIdFuncionario = vhscIdFuncionario;
       this.vhscNome = vhscNome;
       this.vhscCpf = vhscCpf;
       this.vhscDataNascimento = vhscDataNascimento;
       this.vhscEmail = vhscEmail;
       this.vhscTelefone = vhscTelefone;
       this.vhscCargo = vhscCargo;
       this.vhscSalario = vhscSalario;
    }
   
     @Id

    
    @Column(name="VHSC_idFuncionario", unique=true, nullable=false)
    public int getVhscIdFuncionario() {
        return this.vhscIdFuncionario;
    }
    
    public void setVhscIdFuncionario(int vhscIdFuncionario) {
        this.vhscIdFuncionario = vhscIdFuncionario;
    }

    
    @Column(name="VHSC_nome", nullable=false, length=100)
    public String getVhscNome() {
        return this.vhscNome;
    }
    
    public void setVhscNome(String vhscNome) {
        this.vhscNome = vhscNome;
    }

    
    @Column(name="VHSC_cpf", nullable=false, length=14)
    public String getVhscCpf() {
        return this.vhscCpf;
    }
    
    public void setVhscCpf(String vhscCpf) {
        this.vhscCpf = vhscCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VHSC_dataNascimento",length=10)
    public Date getVhscDataNascimento() {
        return this.vhscDataNascimento;
    }
    
    public void setVhscDataNascimento(Date vhscDataNascimento) {
        this.vhscDataNascimento = vhscDataNascimento;
    }

    
    @Column(name="VHSC_email", nullable=false, length=80)
    public String getVhscEmail() {
        return this.vhscEmail;
    }
    
    public void setVhscEmail(String vhscEmail) {
        this.vhscEmail = vhscEmail;
    }

    
    @Column(name="VHSC_telefone", nullable=false, length=15)
    public String getVhscTelefone() {
        return this.vhscTelefone;
    }
    
    public void setVhscTelefone(String vhscTelefone) {
        this.vhscTelefone = vhscTelefone;
    }

    
    @Column(name="VHSC_cargo", nullable=false, length=50)
    public String getVhscCargo() {
        return this.vhscCargo;
    }
    
    public void setVhscCargo(String vhscCargo) {
        this.vhscCargo = vhscCargo;
    }

    
    @Column(name="VHSC_salario", nullable=false, length=100)
    public String getVhscSalario() {
        return this.vhscSalario;
    }
    
    public void setVhscSalario(String vhscSalario) {
        this.vhscSalario = vhscSalario;
    }
@Override
    public String toString() {
        return this.vhscIdFuncionario+ " - " + this.vhscNome;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof VhscFuncionarios) {
            VhscFuncionarios vhscFuncionarios = (VhscFuncionarios) object;
            if (vhscFuncionarios.getVhscIdFuncionario()== this.getVhscIdFuncionario()) {
                return true;
            }
        }
        return false;
}



}


