package bean;
// Generated 12/10/2025 22:26:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VhscVendas generated by hbm2java
 */
@Entity
@Table(name="vhsc_vendas"
    ,catalog="db_vitor_carvalho"
)
public class VhscVendas  implements java.io.Serializable {


     private int vhscIdVenda;
     private String vhscNomeCliente;
     private String vhscNomeLivro;
     private Date vhscDataVenda;
     private int vhscQuantidade;
     private BigDecimal vhscValorTotal;
     private String vhscFormaPagamento;
     private Set vhscVendasProdutoses = new HashSet(0);

    public VhscVendas() {
    }

	
    public VhscVendas(int vhscIdVenda, String vhscNomeCliente, String vhscNomeLivro, Date vhscDataVenda, int vhscQuantidade, BigDecimal vhscValorTotal, String vhscFormaPagamento) {
        this.vhscIdVenda = vhscIdVenda;
        this.vhscNomeCliente = vhscNomeCliente;
        this.vhscNomeLivro = vhscNomeLivro;
        this.vhscDataVenda = vhscDataVenda;
        this.vhscQuantidade = vhscQuantidade;
        this.vhscValorTotal = vhscValorTotal;
        this.vhscFormaPagamento = vhscFormaPagamento;
    }
    public VhscVendas(int vhscIdVenda, String vhscNomeCliente, String vhscNomeLivro, Date vhscDataVenda, int vhscQuantidade, BigDecimal vhscValorTotal, String vhscFormaPagamento, Set vhscVendasProdutoses) {
       this.vhscIdVenda = vhscIdVenda;
       this.vhscNomeCliente = vhscNomeCliente;
       this.vhscNomeLivro = vhscNomeLivro;
       this.vhscDataVenda = vhscDataVenda;
       this.vhscQuantidade = vhscQuantidade;
       this.vhscValorTotal = vhscValorTotal;
       this.vhscFormaPagamento = vhscFormaPagamento;
       this.vhscVendasProdutoses = vhscVendasProdutoses;
    }
   
     @Id 

    
    @Column(name="VHSC_idVenda", unique=true, nullable=false)
    public int getVhscIdVenda() {
        return this.vhscIdVenda;
    }
    
    public void setVhscIdVenda(int vhscIdVenda) {
        this.vhscIdVenda = vhscIdVenda;
    }

    
    @Column(name="VHSC_nomeCliente", nullable=false, length=100)
    public String getVhscNomeCliente() {
        return this.vhscNomeCliente;
    }
    
    public void setVhscNomeCliente(String vhscNomeCliente) {
        this.vhscNomeCliente = vhscNomeCliente;
    }

    
    @Column(name="VHSC_nomeLivro", nullable=false, length=150)
    public String getVhscNomeLivro() {
        return this.vhscNomeLivro;
    }
    
    public void setVhscNomeLivro(String vhscNomeLivro) {
        this.vhscNomeLivro = vhscNomeLivro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VHSC_dataVenda", nullable=false, length=10)
    public Date getVhscDataVenda() {
        return this.vhscDataVenda;
    }
    
    public void setVhscDataVenda(Date vhscDataVenda) {
        this.vhscDataVenda = vhscDataVenda;
    }

    
    @Column(name="VHSC_quantidade", nullable=false)
    public int getVhscQuantidade() {
        return this.vhscQuantidade;
    }
    
    public void setVhscQuantidade(int vhscQuantidade) {
        this.vhscQuantidade = vhscQuantidade;
    }

    
    @Column(name="VHSC_valorTotal", nullable=false, precision=10)
    public BigDecimal getVhscValorTotal() {
        return this.vhscValorTotal;
    }
    
    public void setVhscValorTotal(BigDecimal vhscValorTotal) {
        this.vhscValorTotal = vhscValorTotal;
    }

    
    @Column(name="VHSC_formaPagamento", nullable=false, length=20)
    public String getVhscFormaPagamento() {
        return this.vhscFormaPagamento;
    }
    
    public void setVhscFormaPagamento(String vhscFormaPagamento) {
        this.vhscFormaPagamento = vhscFormaPagamento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhscVendas")
    public Set getVhscVendasProdutoses() {
        return this.vhscVendasProdutoses;
    }
    
    public void setVhscVendasProdutoses(Set vhscVendasProdutoses) {
        this.vhscVendasProdutoses = vhscVendasProdutoses;
    }




}


