package bean;
// Generated 12/10/2025 22:26:10 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VhscVendas generated by hbm2java
 */
@Entity
@Table(name="vhsc_vendas"
    ,catalog="db_vitor_carvalho"
)
public class VhscVendas  implements java.io.Serializable {


     private int vhscIdVenda;
     private VhscClientes vhscNomeCliente;
     private VhscProdutos vhscNomeLivro;
     private Date vhscDataVenda;
     private int vhscQuantidade;
     private double vhscValorTotal;
     private String vhscFormaPagamento;
     

    public VhscVendas() {
    }

	
    public VhscVendas(int vhscIdVenda, VhscClientes vhscNomeCliente, VhscProdutos vhscNomeLivro, Date vhscDataVenda, int vhscQuantidade, double vhscValorTotal, String vhscFormaPagamento) {
        this.vhscIdVenda = vhscIdVenda;
        this.vhscNomeCliente = vhscNomeCliente;
        this.vhscNomeLivro = vhscNomeLivro;
        this.vhscDataVenda = vhscDataVenda;
        this.vhscQuantidade = vhscQuantidade;
        this.vhscValorTotal = vhscValorTotal;
        this.vhscFormaPagamento = vhscFormaPagamento;
    }
    public VhscVendas(int vhscIdVenda, VhscClientes vhscNomeCliente, VhscProdutos vhscNomeLivro, Date vhscDataVenda, int vhscQuantidade, double vhscValorTotal, String vhscFormaPagamento, Set vhscVendasProdutoses) {
       this.vhscIdVenda = vhscIdVenda;
       this.vhscNomeCliente = vhscNomeCliente;
       this.vhscNomeLivro = vhscNomeLivro;
       this.vhscDataVenda = vhscDataVenda;
       this.vhscQuantidade = vhscQuantidade;
       this.vhscValorTotal = vhscValorTotal;
       this.vhscFormaPagamento = vhscFormaPagamento;
      
    }
   
     @Id 

    
    @Column(name="VHSC_idVenda", unique=true, nullable=false)
    public int getVhscIdVenda() {
        return this.vhscIdVenda;
    }
    
    public void setVhscIdVenda(int vhscIdVenda) {
        this.vhscIdVenda = vhscIdVenda;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VHSC_nomeCliente")
    public VhscClientes getVhscClientes() {
        return this.vhscNomeCliente;
    }
    
    public void setVhscClientes(VhscClientes vhscClientes) {
        this.vhscNomeCliente = vhscClientes;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VHSC_nomeLivro")
    public VhscProdutos getVhscProdutos() {
        return this.vhscNomeLivro;
    }
    
    public void setVhscProdutos(VhscProdutos vhscProdutos) {
        this.vhscNomeLivro = vhscProdutos;
    }

    
   

    @Temporal(TemporalType.DATE)
    @Column(name="VHSC_dataVenda",length=10)
    public Date getVhscDataVenda() {
        return this.vhscDataVenda;
    }
    
    public void setVhscDataVenda(Date vhscDataVenda) {
        this.vhscDataVenda = vhscDataVenda;
    }

    
    @Column(name="VHSC_quantidade")
    public int getVhscQuantidade() {
        return this.vhscQuantidade;
    }
    
    public void setVhscQuantidade(int vhscQuantidade) {
        this.vhscQuantidade = vhscQuantidade;
    }

    
    @Column(name="VHSC_valorTotal", nullable=false, precision=10)
    public double getVhscValorTotal() {
        return this.vhscValorTotal;
    }
    
    public void setVhscValorTotal(double vhscValorTotal) {
        this.vhscValorTotal = vhscValorTotal;
    }

    
    @Column(name="VHSC_formaPagamento",  length=20)
    public String getVhscFormaPagamento() {
        return this.vhscFormaPagamento;
    }
    
    public void setVhscFormaPagamento(String vhscFormaPagamento) {
        this.vhscFormaPagamento = vhscFormaPagamento;
    }






}


