package bean;
// Generated 12/10/2025 22:26:10 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VhscVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="VHSC_Vendas_produtos"
    ,catalog="db_vitor_carvalho"
)
public class VhscVendasProdutos  implements java.io.Serializable {


     private int vhscIdVendaProduto;
     private VhscProdutos vhscProdutos;
     private VhscVendas vhscVendas;
     private int vhscQuantidade;
     private double vhscPrecoUnitario;

    public VhscVendasProdutos() {
    }

    public VhscVendasProdutos( VhscProdutos vhscProdutos, VhscVendas vhscVendas, int vhscQuantidade, double vhscPrecoUnitario) {
       
       this.vhscProdutos = vhscProdutos;
       this.vhscVendas = vhscVendas;
       this.vhscQuantidade = vhscQuantidade;
       this.vhscPrecoUnitario = vhscPrecoUnitario;
    }
   
      @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="VHSC_idVendaProduto", unique=true, nullable=false)
    public int getVhscIdVendaProduto() {
        return this.vhscIdVendaProduto;
    }
    
    public void setVhscIdVendaProduto(int vhscIdVendaProduto) {
        this.vhscIdVendaProduto = vhscIdVendaProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VHSC_idProdutos", nullable=false)
    public VhscProdutos getVhscProdutos() {
        return this.vhscProdutos;
    }
    
    public void setVhscProdutos(VhscProdutos vhscProdutos) {
        this.vhscProdutos = vhscProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VHSC_idVenda", nullable=false)
    public VhscVendas getVhscVendas() {
        return this.vhscVendas;
    }
    
    public void setVhscVendas(VhscVendas vhscVendas) {
        this.vhscVendas = vhscVendas;
    }

    
    @Column(name="VHSC_quantidade", nullable=false)
    public int getVhscQuantidade() {
        return this.vhscQuantidade;
    }
    
    public void setVhscQuantidade(int vhscQuantidade) {
        this.vhscQuantidade = vhscQuantidade;
    }

    
    @Column(name="VHSC_precoUnitario", nullable=false, precision=10)
    public double getVhscPrecoUnitario() {
        return this.vhscPrecoUnitario;
    }
    
    public void setVhscPrecoUnitario(double vhscPrecoUnitario) {
        this.vhscPrecoUnitario = vhscPrecoUnitario;
    }




}


